<a href="https://colab.research.google.com/github/Annada234/Annada234/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY
Numpy is a fundamental library for scientific computing in python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.In this lesson,we will cover the basics of Numpy,focusing on arrays and vectorized operations.


In [ ]:
import numpy as np
##create array using numpy
##create 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(5,1)#5 rows and 1 columns#reshape in 2D array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])#2D array
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1)#start,end,step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item Size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item Size(in bytes): 8


In [ ]:
##Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

##Element wise addition
print("Addition:", arr1+arr2)

##Element wise substraction
print("Substraction:", arr1-arr2)

##Element wise multiplication
print("Multiplication:", arr1*arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]


In [ ]:
##Universal Function
arr= np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))
## exponential
print(np.exp(arr))
## sin
print(np.sin(arr))
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [ ]:
##Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
import numpy as np

## Statistical concepts--Normalization
##to have a mean of 0 and standard of 1
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data-mean)/ std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#mean
mean = np.mean(data)
print("mean:", mean)
#median
median = np.median(data)
print("median:", median)
#standard deviation
std_dev = np.std(data)
print("standard deviation:", std_dev)
#variance
variance = np.var(data)
print("variance:", variance)

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [ ]:
##logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<8)]

array([6, 7])